name: PR Build and Test

on:
  # Only run on pull requests, not on pushes to main
  # This prevents conflicts with release workflow
  pull_request:
    branches: [ main, develop ]
  # Allow manual triggering for testing
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Lint code
      run: npm run lint
      continue-on-error: true
      
    - name: Build icons
      run: npm run build:icons
      
    - name: Build application
      run: npm run build
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: pairkiller-build-${{ github.sha }}
        path: |
          dist/*.exe
          dist/*.exe.blockmap
          dist/latest.yml
        retention-days: 7

